version: 'latest'
services:
  postgres:
    image: postgres
    ports:
      5432:5432
  
  user_app:
    build: 
      context: ./
      dockerfile: DockerFile
    

  environment:
    DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres

  ports:
    - 3000:3000
  depends_on:
    - postgres